### ISSUE TITLE
move overwrite

### ISSUE THREAD

**Issue by mike-aungsan** [coolaj86/utile-fs#9]
Should let move function take overwrite opts. Thanks

**Comment by coolaj86** [comment]
Take a look at https://github.com/coolaj86/utile-fs/blob/master/fs.extra/fs.copy.js#L9 If you port that change over to fs.move and put in a pull request I'll give you access to merge and publish to npm.

**Comment by phoenisx** [comment]
I guess it already does, as it extends fs.copy functionalities...

Try Passing `{overwrite: true}`, as shown below:

```js
fs.move("[SOURCE_PATH]", "[DEST_PATH]", {overwrite: true}, function (err) { } );
```

**Comment by Ciao121** [comment]
@Shub1427 
Using 
`{overwrite: true}
`
I get this:
```
C:\Users\myuser\Desktop\myconverter\node_modules\fs.extra\fs.move.js:29
        return cb(new Error("File " + dst + " exists."));
               ^
TypeError: cb is not a function
    at C:\Users\myuser\Desktop\myconverter\node_modules\fs.extra\fs.move.js:29:16
    at FSReqWrap.oncomplete (fs.js:154:5)
```

Windows 10
